source "https://rubygems.org"

gem "rails", "~> 7.2.1"
gem "sprockets-rails"
gem "sqlite3", "~> 1.6.9"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"

gem 'rack-cors'
gem "redis", ">= 4.0.1"

gem "tzinfo-data", platforms: %i[ mingw x64_mingw jruby ]
gem "bootsnap", require: false

# Bootstrap
gem 'bootstrap', '~> 5.3.0'
gem 'sassc-rails'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ], require: "debug/prelude"
  gem "rspec-rails"
  gem "capybara"

  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
  gem "byebug"
  gem 'pry', '~> 0.14.2'
end

group :test do
  gem "selenium-webdriver"
end

gem "cpf_cnpj"

gem "vite_rails", "~> 3.0"

# Firebase token validation
gem "jwt", "~> 2.7"
gem "net-http"

# BCrypt para hash de senha (mesmo que não usemos para autenticação, a coluna precisa de um valor)
gem "bcrypt", "~> 3.1.7"

# Paginação
gem "kaminari"
